const TASK_ENDPOINT = 'http://localhost:5000/tasks';
const POST_HTTP_METHOD = 'POST';
const PUT_HTTP_METHOD = 'PUT';
const DELETE_HTTP_METHOD = 'DELETE';

export {
    TASK_ENDPOINT,
    POST_HTTP_METHOD,
    PUT_HTTP_METHOD,
    DELETE_HTTP_METHOD,
}